### ISSUE TITLE
Flash not work in Android

### ISSUE THREAD

**Issue by dulkith** [clovisnicolas/flutter_lamp#10]
D/ViewRootImpl(16291): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(16291): ViewPostImeInputStage processPointer 1
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): Failed to handle method call
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): java.lang.RuntimeException: getParameters failed (empty parameters)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at android.hardware.Camera.native_getParameters(Native Method)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at android.hardware.Camera.getParameters(Camera.java:1996)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at plugins.flutter.lamp.lamp.LampPlugin.turn(LampPlugin.java:63)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at plugins.flutter.lamp.lamp.LampPlugin.onMethodCall(LampPlugin.java:34)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at android.app.ActivityThread.main(ActivityThread.java:7325)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(16291): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/flutter (16291): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, getParameters failed (empty parameters), null)
E/flutter (16291): #0      StandardMethodCodec.decodeEnvelope 
E/flutter (16291): #1      MethodChannel.invokeMethod 
E/flutter (16291): <asynchronous suspension>
E/flutter (16291): #2      Lamp.turnOn
E/flutter (16291): #3      _CameraHomeScreenState.build.<anonymous closure>
E/flutter (16291): #4      _InkResponseState._handleTap 
E/flutter (16291): #5      _InkResponseState.build.<anonymous closure> 
E/flutter (16291): #6      GestureRecognizer.invokeCallback 
E/flutter (16291): #7      TapGestureRecognizer._checkUp 
E/flutter (16291): #8      TapGestureRecognizer.handlePrimaryPointer 
E/flutter (16291): #9      PrimaryPointerGestureRecognizer.handleEvent 
E/flutter (16291): #10     PointerRouter._dispatch 
E/flutter (16291): #11     PointerRouter.route 
E/flutter (16291): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
E/flutter (16291): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
E/flutter (16291): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
E/flutter (16291): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
E/flutter (16291): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
E/flutter (16291): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (16291): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (16291): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (16291): #20     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (16291): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
E/flutter (16291):

**Comment by developerpaaji** [comment]
Same here

**Comment by Shavneet** [comment]
camera permission not working for flashlight , Have to restart app to make it work for flashlight using lamp 0.0.6 plugin #9
Posted this issue 3 months ago and still there is no response from flutter community . What should i do ?

**Comment by malikdoksoz** [comment]
Because **import android.hardware.Camera** deprecated

**Comment by Shavneet** [comment]
So what is the solution for this ?

**Comment by GustavoFigueira** [comment]
2020... And any solution?

**Comment by namittoppr** [comment]
@malikdoksoz then solution? @GustavoFigueira did you find any solution?

**Comment by dulkith** [comment]
@namittoppr use this, i solve my problem from this: [LINK](https://github.com/hramaroson/flutter_cameraview)

**Comment by 120011676** [comment]
+1
