### ISSUE TITLE
Flashlight not working on Android

### ISSUE THREAD

**Issue by AlexBacich** [clovisnicolas/flutter_lamp#6]
Flash isn't working.
Tried to start on example - it gives an error: 

E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): Failed to handle method call
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): java.lang.RuntimeException: getParameters failed (empty parameters)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at android.hardware.Camera.native_getParameters(Native Method)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at android.hardware.Camera.getParameters(Camera.java:2027)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at plugins.flutter.lamp.lamp.LampPlugin.turn(LampPlugin.java:63)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at plugins.flutter.lamp.lamp.LampPlugin.onMethodCall(LampPlugin.java:34)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at android.os.MessageQueue.next(MessageQueue.java:375)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at android.os.Looper.loop(Looper.java:225)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at android.app.ActivityThread.main(ActivityThread.java:6589)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(31729): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by adlanarifzr** [comment]
Same error happened.

**Comment by agreensh** [comment]
Same error.

E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): Failed to handle method call
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): java.lang.RuntimeException: getParameters failed (empty parameters)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at android.hardware.Camera.native_getParameters(Native Method)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at android.hardware.Camera.getParameters(Camera.java:1952)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at plugins.flutter.lamp.lamp.LampPlugin.turn(LampPlugin.java:63)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at plugins.flutter.lamp.lamp.LampPlugin.onMethodCall(LampPlugin.java:34)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/MethodChannel#github.com/clovisnicolas/flutter_lamp(14908): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by markflarup** [comment]
I have tried to make the example code work on a Nexus 5 running Nougat (7.1.2) without any luck. I have granted my application permissions to use the camera without affecting the outcome. The flash is working as I can toggle it from the dropdown menu. 
However, when I run it on a Oneplus5 with Oreo I can make it work. Has anybody else encountered a similar problem?

The only outcome I get in the terminal is the initial check: `I/flutter (16233): Device has flash ? true`

I have specified version `lamp: 0.0.6` as dependency.

**Comment by agreensh** [comment]
> I have tried to make the example code work on a Nexus 5 running Nougat (7.1.2) without any luck. I have granted my application permissions to use the camera without affecting the outcome. The flash is working as I can toggle it from the dropdown menu.
> However, when I run it on a Oneplus5 with Oreo I can make it work. Has anybody else encountered a similar problem?
> 
> The only outcome I get in the terminal is the initial check: `I/flutter (16233): Device has flash ? true`
> 
> I have specified version `lamp: 0.0.6` as dependency.

If you need a solution now, look at Issue #7 and follow use of torch.zip plugin.

**Comment by markflarup** [comment]
> 
> If you need a solution now, look at Issue #7 and follow use of torch.zip plugin.

I tried to make it work without any luck. I will try to document my steps to figure out where I went wrong. Thanks for the reply. 

Just a thought: have you considered closing this issue?

**Comment by agreensh** [comment]
I haven't closed this issue as, even though I've worked around it, it is still an issue with this package (flutter_lamp).
